# 1. Computation with Universal Functions

Namely, NumPy provides an easy and flexible interface to optimized computation with arrays of data. 

Computation on NumPy arrays can be very fast, or it can be very slow. 

The key to making it fast is to use vectorized operations, generally implemented through NumPy’s ***universal functions (ufuncs). ***

### 1) The Slowness of Loops

The relative sluggishness of Python generally manifests itself in situations where many small operations are being repeated - for instance, looping over arrays to operate on each element. For example, imagine the code below :


In [3]:
%%timeit
import numpy as np
np.random.seed(0)
def compute_reciprocals(values) :
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)


9.17 µs ± 44.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


This implementation probably feels fairly natural to someone from C or Java background. 
But if we measure the execution time of this code for a large input, we see that this operation is very surprisingly slow. 

Bottleneck here is **not the operations themselves, but the type-checking and function dispatches **that CPython must do at each cycle of the loop.

### 2) Introducing Ufuncs

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.

- Ufuncs exist in two flavors : unary ufuncs and binary ufuncs.
    - np.add +
    - np.subtract -
    - np.negative -
    - np.multiply *
    - np.divide /
    - np.floor_divide //
    - np.power **
    - np.mod %
    - np.absolute, np.abs , abs(x)

- Trigonometric functions
    - theta = np.linspace(0, np.pi, 3)
    - np.sin(theta)    / np.arcsin(theta)
    - np.cos(theta)    / np.arccos(theta)
    - np.tan(theta)    / np.arctan(theta)
    
- Exponents and Logaithms
    - x = [1, 2, 3]
    - np.exp(x)
    - np.exp2(x)    = 2^x
    - np.power(3, x)    = 3^x
    - x = [1, 2, 4, 10]
    - np.log(x)
    - np.log2(x)
    - np.log10(x)
    - when the numbers are very small
    
    print(“exp(x) - 1 =”, np.expm1(x) )
    
    print(“log(1+x) =”, np.log1p(x))


### 3) Advanced Ufunc Features

###### a) Specifying Output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. 

In [7]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[  0.  10.  20.  30.  40.]
[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


If we had instead written y[::2] = 2^x, 

**this would have resulted in the creation of a temporary array to hold the results of 2 ^x, followed by a second operation copying those values into the y array.** 

For large arrays, the memory savings from use of “the out” can be significant.


###### b) Aggregates

For binary ufuncs, there are some interesting aggregate that can be computed directly from the object. For example, if we’d like to reduce an array with a particular operation, we can use the reduce method of any ufunc.

**  A reduce repeatedly applies a given operation to the elements of an array until only a single result remains. **

In [8]:
 x = np.arange(1, 6)
np.add.reduce(x)  #out = 15, same as np.sum
np.multiply.reduce(x)  #out = 120, same as np.prod
np.add.accumulate(x)     #out = [1,3,6,10,15], same as np.cumsum / np.cumprod

array([ 1,  3,  6, 10, 15])

###### c) Outer Products

Finally, any ufunc can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table

In [10]:
x = np.arange(1,6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

###### d) Some operations

In [11]:
M = np.random.random( (3,4) )
print(M.sum()) #overall sum
print(M.min(axis=0))    # min val of each column
print(M.max(axis=1)) #max val of each row

6.7184399189
[ 0.4236548   0.38344152  0.07103606  0.0871293 ]
[ 0.891773    0.96366276  0.92559664]


In [14]:
print(np.argmin ) # find index of minimum value
print(np.argmax) # “”
print(np.percentile) # compute rank-based statistics
print(np.any(x>8) )   # Evaluate whether any elements are true
print(np.all(x>8)) # Evaluate whether all elements are true

<function argmin at 0x7f47642d3158>
<function argmax at 0x7f47642d30d0>
<function percentile at 0x7f47641b06a8>
False
False
