유사도를 측정하는 여러가지 방법들이 있다.

여기에는 그 방법들을 정리해놓겠다.

# Similarity Measures

### 1. Euclidean Measure

### 2. Mahalanobis Distance

### 3. Minkowsky Distance

### 4. Levenshtein Distance (Edit Distance)


Levenshtein Distance (Edit Distance)

https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Algorithm


https://people.cs.pitt.edu/~kirk/cs1501/Pruhs/Spring2006/assignments/editdistance/Levenshtein%20Distance.htm


String metric for measuring the edit distance between two sequences. Minimum number of operations of a single character, or transposition of two adjacent characters required to change one word into the other.


** Damerau-Levenshtein distance differs from the classical Levenshtein distance by including transpositions to insertions, deletions and substitutions.


Code attached to assignment #2.



### 5. Jaccard Similarity


https://www.cs.utah.edu/~jeffp/teaching/cs5140-S15/cs5140/L4-Jaccard+nGram.pdf

 Jaccard Index (Intersection over Union, Jaccard similarity coefficient)

> used for comparing the similarity and diversity of sample sets.

> is known as a method to test the similarity btw groups

> Jaccard similarity J(A,B) is defined as dividing the size of intersection with the size of Union. (Intersection over Union)

•Application to documents & Words



Bag of words vs. k-Grams ( k-shingle )
1.Bag of words model, each document is treated as an unordered set of works.


2.k-Gram model, consecutive set of k words.


a.I am Sam, Sam I am  -> [I am] [am Sam] ,[Sam Sam] , …


b.professional -> [pr] [ro] [of] [fe], …



Code is attached to assignment #2



### 6. Cosine Similarity

# Rank Correlation

### 1. Kendall Rank Correlation Coefficient

In [365]:
import re

### Regex Methods

- **regex.match(string, pos, endpos)**
<br>if "beginning" of string matches the regex, returns a corresponding match object

- **regex.fullmatch(string, pos, endpos)**
<br>if the "whole" string matches the regex, returnsa corresponding match object

- **regex.split(string, maxsplit= 0)**
<br>identical to the split() function with given pattern

- **regex.findall(string, pos, end)**
<br>return all matches of pattern in string, as a list of strings

- **regex.finditer(string, pos, end) **
<br>return an iterator yielding match objects


In [366]:
# fullmatch example
pattern = re.compile("o[gh]")
print(pattern.fullmatch("dog")) # no match as "o" is not at the start of "dog"
print(pattern.fullmatch("ogre"))
print(pattern.fullmatch("doggie", 1, 3))

None
None
<_sre.SRE_Match object; span=(1, 3), match='og'>


In [367]:
# split example
re.split('[a-f+]', '0a3B9', flags=re.IGNORECASE)

['0', '3', '9']

### Regex Group

- **match.group**
<br> returns one or more subgroups of the match

- **match.groups()**
<br>return a tuple containing all the subgroups of the match, from 1 upto however many groups there are in the pattern

- **match.groupdict() **
<br>return a dict containing all the named subgroups of the match, keyed by the subgroup name

In [368]:
# group example
m = re.match(r"(\w+) (\w+)", "Isaac newton, Physicist")
print(m.group(0))  # The entire match
print(m.group(1))  # The first parenthesized subgroup
print(m.group(2))  # The second parenthesized subgroup
print(m.group(1,2))# Mtp given as tuple

m[2] # same as m.group(2)

Isaac newton
Isaac
newton
('Isaac', 'newton')


'newton'

In [369]:
# if a group matches mtp times, only the last match is accessible.
m = re.match(r"(..)+", "a1b2c3") # matches 3 times
m.group(1)

'c3'

### Regex Complement

Both patterns and strings to be searched can be Unicode strings as well as 8-bit strings. However, they cannot be mixed.

Regex use the baskslash character ("\") to indicate special forms or to allow special char to be used without invoking their special meaning. This collide's Python's usage of the same char for the same purpose in string literal.

For example, to match a literal backslash, we should use '\\\\' because regex must be \\, and each backslash must be expressed as \\ inside a regular Python literal.

-> The Solution is to use `r"\n"`.

In [370]:
import re
# search는 처음으로 일치하는 매치 오브젝트를 반환한다.
sent = 'b <a> b <c>'
re.search('<.*>', sent)

<_sre.SRE_Match object; span=(2, 11), match='<a> b <c>'>

In [371]:
# match는 string의 첫 부분부터 일치하는 오브젝트를 반환한다.
re.match('<.*>', sent)

#### *?, +?, ??

The `'*', '+', and '?'` qualifiers are all greedy ; they match as much text as possible.<br>
Sometimes, this behavior isn't desired; if the RE `<.*>` is matched against `<a> b <c>`, it will match the entire string, not just `<a>`. <br>
Adding ? after it performs the match in non-greedy or minimal fashion.

아래의 예를 살펴보자

In [372]:
# greedy way -> sent 전체 문장이 일치한다

sent = 'b <a> b <c>'
re.search('<.*>', sent)

<_sre.SRE_Match object; span=(2, 11), match='<a> b <c>'>

In [373]:
# non greedy way -> minimal하게 <a>만 일치한다.

re.search('<.*?>', sent)

<_sre.SRE_Match object; span=(2, 5), match='<a>'>

#### Other Extensions

- (?...) : extension notation
- (?aiLmsux) : Entire flagging (re.A, re.I, re.L ,...). They should be used first in the expression string.
- (?:...) : Non-capturing version of regular parentheses. Substring matched cannot be retrieved.
- (?imsx-imsx:...) : Sets or Removes the corresponding flags.
- (?P\<name\>...) : Similar to regular parentheses, but the substring matched is accessible.
- (?P=name) : back-reference to a named group; matches whatever was matched by earlier-group
- (?#...) : Comment, ignored
- (?=...) : Lookahead assertion, matches if ... matches next <br> For example, Issac (?=Asimov) match 'Isaac' only if it's followed by 'Asimov'
- (?!...) : negative Lookahead assertion, matches if ... does not match next.<br> For example, Isaac (?!Asimov) match 'Isaac' only if it's not followed by 'Asimov'
- (?<=...) : Positive lookbehind assertion; matches if the cur pos in the string is preceded by a match for ... that ends at the cur pos.
- (?<!...) : negative Lookbehind assertion
- (? (id/name) yes-pattern | no-pattern) : if the group with given id exists, match with yes-pattern, otw, no-pattern

#### Referencing in different ways

1. in the same pattern itself
    1. (?P=name)
    2. \\1

2. when processing match object m
    1. m.group('name')
    2. m[1]
    3. m.end('name')

3. in a string passed to the repl argument of re.sub()
    1. \g<name>
    2. \\g<1>
    3. \\1

### Data Selection in DataFrame

#### 1. DataFrame as a dictionary

In [374]:
import pandas as pd

area = pd.Series( {'California' : 423967, 'Texas' : 695662, 'New York' : 141297, 
                   'Florida': 170312, 'Illinois': 12882135})

pop = pd.Series( {'California': 3833521, 'Texas': 26448193, 'New York': 19651127,
                 'Florida': 19552860, 'Illinois': 12882135})

data = pd.DataFrame({'area' : area, 'pop' : pop})
data

area       pop
California    423967   3833521
Florida       170312  19552860
Illinois    12882135  12882135
New York      141297  19651127
Texas         695662  26448193

In [375]:
print(data.area is data['area'])
data['area'] # same as data.area

True


California      423967
Florida         170312
Illinois      12882135
New York        141297
Texas           695662
Name: area, dtype: int64

In [376]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California    423967   3833521    9.042027
Florida       170312  19552860  114.806121
Illinois    12882135  12882135    1.000000
New York      141297  19651127  139.076746
Texas         695662  26448193   38.018740

#### 2. DataFrame as two-dimensional array

In [377]:
# first row
print(data.values[0])

# raw underlying data
print(data.values)

# Transpose
print(data.T)

# Col access
print(data['area'])

[  4.23967000e+05   3.83352100e+06   9.04202686e+00]
[[  4.23967000e+05   3.83352100e+06   9.04202686e+00]
 [  1.70312000e+05   1.95528600e+07   1.14806121e+02]
 [  1.28821350e+07   1.28821350e+07   1.00000000e+00]
 [  1.41297000e+05   1.96511270e+07   1.39076746e+02]
 [  6.95662000e+05   2.64481930e+07   3.80187404e+01]]
           California       Florida    Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  12882135.0  1.412970e+05  6.956620e+05
pop      3.833521e+06  1.955286e+07  12882135.0  1.965113e+07  2.644819e+07
density  9.042027e+00  1.148061e+02         1.0  1.390767e+02  3.801874e+01
California      423967
Florida         170312
Illinois      12882135
New York        141297
Texas           695662
Name: area, dtype: int64


In [378]:
# Using different indexers

print(data.iloc[:3, :2])
data.iloc[0, 2] = 90
print(data.loc[:'Illinois', :'pop'])
print(data.ix[:3, :'pop'])

                area       pop
California    423967   3833521
Florida       170312  19552860
Illinois    12882135  12882135
                area       pop
California    423967   3833521
Florida       170312  19552860
Illinois    12882135  12882135
                area       pop
California    423967   3833521
Florida       170312  19552860
Illinois    12882135  12882135


/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix


In [379]:
# masking + fancy indexing
data.loc[ data.density > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

#### 3. Additional Indexixng Conventions

While indexing refers to columns, slicing refers to rows

In [380]:
# Indexing refers to columns
data['area']

California      423967
Florida         170312
Illinois      12882135
New York        141297
Texas           695662
Name: area, dtype: int64

In [381]:
# Slicing refers to rows
data['Florida' : 'Illinois']

area       pop     density
Florida     170312  19552860  114.806121
Illinois  12882135  12882135    1.000000

### (NOT HERE) Ufuncs: Index Preservation
Any NumPy ufunc will work on Pandas Series and DataFrame Objects

In [382]:
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
df = pd.DataFrame(rng.randint(0, 10, (3,4)), columns=['A', 'B', 'C', 'D'])
print(np.exp(ser))
print(np.exp(df))
print(np.sin(df*np.pi / 4))

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64
             A            B           C            D
0   403.428793  8103.083928    7.389056   403.428793
1  1096.633158    54.598150   20.085537  1096.633158
2  1096.633158     7.389056  148.413159    54.598150
          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16


### (NOT HERE) Handling Missing Data

1. Trade-offs in Missing data conventions
    <br>1) using a `mask` that glbally indicates missing values
    <br>2) or choosing a `sentinel` value that indicates a missing entry<br>
2. Missing Data in Pandas
    <br>1) None : Pythonic missing data.
    <br> because None is a Python object, it cannot be used in any arbrtrary NumPy / Pandas array.
    <br>2) NaN : Special floating-point value recognized by all systems.

In [383]:
# Some special NaN operations
a = [1, 2, np.nan]
print(sum(a))       # return nan
print(np.nansum(a)) # return value after operating w/o nan
print(np.nanmin(a))
print(np.nanmax(a))

nan
3.0
1.0
2.0


3) Null : To facilitate this convention, there are several useful methods for detecting, removing, and replacing null values in Pandas

In [384]:
b = pd.DataFrame( {'b' : [1, 2, None ]})
print(b)
print(b.isnull())
print(b.notnull())
print(b.dropna())
print(b.fillna(0))
print(b.fillna(method='ffill')) #forward fill
print(b.fillna(method='bfill')) #backward fill

     b
0  1.0
1  2.0
2  NaN
       b
0  False
1  False
2   True
       b
0   True
1   True
2  False
     b
0  1.0
1  2.0
     b
0  1.0
1  2.0
2  0.0
     b
0  1.0
1  2.0
2  2.0
     b
0  1.0
1  2.0
2  NaN


### (NOT HERE) Hierarchical Indexing (Multi-Indexing)

Data indexed by more than one or two keys. (Pandas : `Panel, Panel 4D Object`)

#### 1. Multi-Index Creation

###### The Bad Way

In [385]:
index = [ ('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), 
        ('Texas', 2000), ('Texas', 2010) ]
populations = [ 33871648, 37253956, 20851820, 25145561, 18976457, 19378102]

pop = pd.Series(populations, index= index)
print(pop)

# messy code to find all event in 2010
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      20851820
(New York, 2010)      25145561
(Texas, 2000)         18976457
(Texas, 2010)         19378102
dtype: int64


(California, 2010)    37253956
(New York, 2010)      25145561
(Texas, 2010)         19378102
dtype: int64

###### The Better Way
**\- Pass a list of two or more index arrays**

In [386]:
df = pd.DataFrame(np.random.rand(4,2), index= [['a', 'a', 'b', 'b'], [1, 2, 1, 2]], columns = ['data1', 'data2'])
df

data1     data2
a 1  0.175772  0.741495
  2  0.960148  0.068158
b 1  0.272201  0.086565
  2  0.711245  0.925397

**\-Pass a dictionary with appropriate tuples as keys**

In [387]:
data = {('California', 2000): 33871648, ('California', 2010): 37253956, ('New York', 2000): 18976457, 
        ('New York', 2010): 19378102, ('Texas', 2000): 20851820, ('Texas', 2010): 25145561 }
pop = pd.Series(data)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [388]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

** \-Explicit Multi-Index Constructor**

In [389]:
# directly from its encoding
pd.MultiIndex(levels= [['a', 'b'], [1, 2]], labels= [[0, 0, 1, 1], [0, 1, 0, 1]])
    # 여기서 라벨은 앞의 level을 받는 것
    # 아래 Cartesian은 자동으로 교차 선택이라면, 여기서는 수동으로 골라주는 것이다.

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [390]:
# from a single list of array
index1 = pd.MultiIndex.from_arrays( [['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

In [391]:
# from a list of tuples
pd.MultiIndex.from_tuples([ ('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [392]:
# from a Cartesian product
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [393]:
# Index를 만든 다음, 아래처럼 reindex를 해준다.
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

**\- Another way - add extra dimension**

In [394]:
pop_df = pop.unstack()
print(pop_df)

#opposite operation
pop_df.stack()
pop

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561


California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

**\-MultiIndex Level Names**

In [395]:
pop.index.names

FrozenList([None, None])

In [396]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

**\-MultiIndex For Columns**

In [397]:
# Hierarchical Indices and columns
index = pd.MultiIndex.from_product( [[2013, 2014], [1, 2]], names= ['year', 'visit'] )
columns = pd.MultiIndex.from_product( [['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names= ['subject', 'type'] )

# mock some data
data = np.round(np.random.randn(4,6), 1)
data[:, ::2]*= 10

# Create the DataFrame
health_data = pd.DataFrame(data, index= index, columns= columns)
health_data

subject      Bob      Guido        Sue     
type          HR Temp    HR Temp    HR Temp
year visit                                 
2013 1     -23.0 -1.8  -1.0 -0.3   9.0 -0.3
     2       3.0  0.2 -10.0 -1.6 -11.0  0.1
2014 1     -11.0 -0.7   4.0  0.5  -8.0 -0.4
     2      -4.0 -1.3  -1.0 -0.2 -11.0 -0.0

#### 2. Indexing and Slicing a MultiIndex

**\-Series**

In [398]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [403]:
pop['California', 2000]

33871648

In [404]:
# partial indexing
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [405]:
# partial slicing
pop['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [410]:
# partial indexing on lower level
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [424]:
print( pop[ pop> 22000000])  # boolean mask
print( pop[ [('California', 2000), ('Texas', 2000)]])  # fancy indexing

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64
state       year
California  2000    33871648
Texas       2000    20851820
dtype: int64


**\-DataFrame**

In [428]:
health_data

subject      Bob      Guido        Sue     
type          HR Temp    HR Temp    HR Temp
year visit                                 
2013 1     -23.0 -1.8  -1.0 -0.3   9.0 -0.3
     2       3.0  0.2 -10.0 -1.6 -11.0  0.1
2014 1     -11.0 -0.7   4.0  0.5  -8.0 -0.4
     2      -4.0 -1.3  -1.0 -0.2 -11.0 -0.0

In [429]:
health_data['Guido', 'HR']

year  visit
2013  1        -1.0
      2       -10.0
2014  1         4.0
      2        -1.0
Name: (Guido, HR), dtype: float64

In [431]:
health_data.iloc[:2, :2]

subject      Bob     
type          HR Temp
year visit           
2013 1     -23.0 -1.8
     2       3.0  0.2

In [432]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1       -23.0
      2         3.0
2014  1       -11.0
      2        -4.0
Name: (Bob, HR), dtype: float64

#### 3. Rearranging Multiple Indices

Many of the MultiIndex slicing operations ***will fail*** if the index is not sorted.

**\-Unsorted Indices**

In [451]:
# Unsorted Data
index = pd.MultiIndex.from_product([ ['a', 'c', 'b'], [1, 2]])
data = pd.Series( np.random.rand(6), index= index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.483173
      2      0.329294
c     1      0.367498
      2      0.059973
b     1      0.386499
      2      0.442006
dtype: float64

In [453]:
# will make an error
try : data['a' : 'b'] 
    
except KeyError as e :
    print("error!")
    print(type(e))
    print(e)

error!
<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


**\-Sorting**

In [455]:
data = data.sort_index()
print(data)

data = data.sortlevel()
print(data)

char  int
a     1      0.483173
      2      0.329294
b     1      0.386499
      2      0.442006
c     1      0.367498
      2      0.059973
dtype: float64
char  int
a     1      0.483173
      2      0.329294
b     1      0.386499
      2      0.442006
c     1      0.367498
      2      0.059973
dtype: float64


/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:4: FutureWarning: sortlevel is deprecated, use sort_index(level=...)


**\-Stacking & Unstacking**

In [458]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [460]:
print(pop.unstack(level = 0))
print("\n", pop.unstack(level = 1))  # default is level 1
print("\n", pop.unstack().stack())

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

 year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

 state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


**\-Index setting and resetting**

In [462]:
# turn the index labels into columns
pop_flat = pop.reset_index(name = 'population')
print(pop_flat)

# Now the reverse
print(pop_flat.set_index(['state', 'year']))

        state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561
                 population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561


#### 4. Data Aggregation on Multi Indices
Pandas has built-in data aggregation methods.

In [475]:
data_mean

subject   Bob      Guido        Sue     
type       HR Temp    HR  Temp   HR Temp
year                                    
2013    -10.0 -0.8  -5.5 -0.95 -1.0 -0.1
2014     -7.5 -1.0   1.5  0.15 -9.5 -0.2

In [480]:
data_mean = health_data.mean(level='year')
print(data_mean,"\n")
print(data_mean.mean(axis = 1, level='type'))

subject   Bob      Guido        Sue     
type       HR Temp    HR  Temp   HR Temp
year                                    
2013    -10.0 -0.8  -5.5 -0.95 -1.0 -0.1
2014     -7.5 -1.0   1.5  0.15 -9.5 -0.2 

type        HR      Temp
year                    
2013 -5.500000 -0.616667
2014 -5.166667 -0.350000
